steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - gcloud
  - functions
  - deploy
  - function-tesla-info
  - --region=us-east4
  - --service-account=service-account-wyze-function@ensure-dev-zone.iam.gserviceaccount.com
  - --entry-point=tesla_state
  - --source=src
  - --trigger-http
  - --runtime=python310
options:
  logging: CLOUD_LOGGING_ONLY
